version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  backend:
    build: ./backend
    container_name: notes_backend
    command: ["/wait-for-postgres.sh", "db", "sh", "-c", "npm run migrate && npm run start"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${BACKEND_PORT}
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: notes_frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}
      PORT: ${FRONTEND_PORT}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

volumes:
  db_data:
